version: '3.4'
services:
  nginx-dev:
    image: twin-city/nginx-dev
    container_name: nginx-dev
    build:
      context: nginx
      target: development
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    environment:
      - APP
      - FRONTEND_HOST
      - FRONTEND_PORT
    ports:
      - "$PORT:80"
