SHELL = /bin/bash

export CURRENT_PATH := $(shell pwd)
export APP = twincity
export APP_VERSION := 0.3

# compose command to merge production file and and dev/tools overrides
export COMPOSE?=docker-compose
export DC_UP_ARGS = --force-recreate #s--build
export DC_BUILD_ARGS = #	--no-cache

#NETWORK
export DC_NETWORK := $(shell echo ${APP} | tr '[:upper:]' '[:lower:]')
export DC_NETWORK_OPT = --opt com.docker.network.driver.mtu=1450
# FRONTEND
export FRONTEND_PORT=3000
export FRONTEND_HOST = frontend
# NGINX
export PORT = 80
# WebGl generated by Unity
export WEBGL_DIR = $(shell dirname ${CURRENT_PATH})/unity-project/WebGL-20220706T081328Z-001/WebGL
# BUILD OPTIONS
export BUILD_DIR =${CURRENT_PATH}/${APP}-build
export FILE_FRONTEND_DIST_APP_VERSION = $(APP)-$(APP_VERSION)-frontend-dist.tar.gz

include ./artifacts
#############
#  Network  #
#############

network-stop:
	docker network rm ${DC_NETWORK}

network:
	@docker network create ${DC_NETWORK_OPT} ${DC_NETWORK} 2> /dev/null; true

##############
#  FRONTEND  #
##############

frontend-dev-build:
	@echo "Build frontend"
	@$(COMPOSE) -f docker-compose-frontend-dev.yml build $(DC_BUILD_ARGS)

frontend-dev: network
	@echo "Listening on port: $(FRONTEND_PORT)"
	@$(COMPOSE) -f docker-compose-frontend-dev.yml up -d $(DC_UP_ARGS)

frontend-dev-exec:
	@echo "Listening on port: $(FRONTEND_PORT)"
	@$(COMPOSE) -f docker-compose-frontend-dev.yml exec frontend-dev sh

frontend-down:
	@$(COMPOSE) -f docker-compose-frontend-dev.yml down


##############
#  NGINX     #
##############

nginx-dev:
	@echo webGl directory is : ${WEBGL_DIR}
	@$(COMPOSE) -f docker-compose-nginx-dev.yml up -d $(DC_UP_ARGS)
nginx-dev-stop:
	@$(COMPOSE) -f docker-compose-nginx-dev.yml down
nginx-dev-exec:
	@$(COMPOSE) -f docker-compose-nginx-dev.yml exec nginx-dev bash
nginx-dev-down:
	@$(COMPOSE) -f docker-compose-nginx-dev.yml down
nginx-dev-build:
	@$(COMPOSE) -f docker-compose-nginx-dev.yml build $(DC_BUILD_ARGS)

nginx-prod:
	@$(COMPOSE) -f docker-compose-nginx.yml up -d $(DC_UP_ARGS)
nginx-down:
	@$(COMPOSE) -f docker-compose-nginx.yml down

###############
# BUILD STAGE #
###############
build: frontend-build nginx-build

frontend-build: frontend-build-dist $(BUILD_DIR)/$(FILE_FRONTEND_DIST_APP_VERSION)

nginx-build:
	@echo building ${APP} nginx
	cp $(BUILD_DIR)/$(FILE_FRONTEND_DIST_APP_VERSION) nginx/
	@$(COMPOSE) -f docker-compose-nginx.yml build $(DC_BUILD_ARGS)

frontend-build-dist:
	@echo building ${APP} frontend in ${FRONTEND}
	@$(COMPOSE) -f docker-compose-frontend-build.yml build $(DC_BUILD_ARGS)


build-dir:
	@if [ ! -d "$(BUILD_DIR)" ] ; then mkdir -p $(BUILD_DIR) ; fi

$(BUILD_DIR)/$(FILE_FRONTEND_DIST_APP_VERSION): build-dir
	$(COMPOSE) -f docker-compose-frontend-build.yml run -T frontend-build sh -c "npm run build > /dev/null 2>&1 && tar czf - build/ -C /app" > $(BUILD_DIR)/$(FILE_FRONTEND_DIST_APP_VERSION)

test:
	echo "test" > test
##############
#  GENERAL   #
##############

dev: frontend-dev nginx-dev
down: frontend-down nginx-dev-down

up: nginx-prod
stop: nginx-down
